title: Deep Chakraborty
position: Ph.D. Student
affiliation: UMass Amherst
email: dchakraborty (at) cs.umass.edu
keywords: deep chakraborty machine learning computer vision
google_scholar: https://scholar.google.com/citations?user=Ld6-470AAAAJ&hl=en
github_link: https://github.com/deepc94/
linkedin: https://www.linkedin.com/in/deepc94/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Deep Chakraborty's homepage
canonical: https://deepc94.github.io/
# remote_theme: yaoyao-liu/minimal-light
